name: flutter_application_tutorial
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_riverpod: ^2.3.7
  firebase_core: ^2.15.1
  cloud_firestore: ^4.8.5
  uuid: ^3.0.7
  firebase_auth: ^4.7.3
  google_fonts: ^4.0.3
  pull_to_refresh: ^2.0.0
  image_cropper: ^1.4.1
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.12
  clipboard: ^0.1.3
  flutter_launcher_icons: ^0.13.1
  flash: ^3.0.5+1
  image_picker: ^1.0.2
  flutter_svg: ^2.0.7
  firebase_storage: ^11.2.6
  firebase_crashlytics: ^3.3.5
  fluttertoast: ^8.2.2
  material_floating_search_bar: ^0.3.7
  flutter_dotenv: ^5.1.0
  freezed_annotation: ^2.4.1
  algolia: ^1.1.2
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
