// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHCTtANJ9nx3OtbOg9brFbovgd69zJxdA',
    appId: '1:89043126170:web:b3ad1c509f8149ef0e5c23',
    messagingSenderId: '89043126170',
    projectId: 'flutter-tutorial-fe59f',
    authDomain: 'flutter-tutorial-fe59f.firebaseapp.com',
    storageBucket: 'flutter-tutorial-fe59f.appspot.com',
    measurementId: 'G-H778JTV1Z8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyGs6V9UxG3HhNZWgNLVHRkUQhdLGAIvU',
    appId: '1:89043126170:android:bf40ae03d093c9980e5c23',
    messagingSenderId: '89043126170',
    projectId: 'flutter-tutorial-fe59f',
    storageBucket: 'flutter-tutorial-fe59f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg3qpj1oWX97o6Rm38aW9RvXtBysxvNj8',
    appId: '1:89043126170:ios:a6b8c148b5e4d5470e5c23',
    messagingSenderId: '89043126170',
    projectId: 'flutter-tutorial-fe59f',
    storageBucket: 'flutter-tutorial-fe59f.appspot.com',
    iosClientId: '89043126170-och0nmoqtu1basnreaje40h1rjjb8ttu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg3qpj1oWX97o6Rm38aW9RvXtBysxvNj8',
    appId: '1:89043126170:ios:3ef0f79f64c9f67e0e5c23',
    messagingSenderId: '89043126170',
    projectId: 'flutter-tutorial-fe59f',
    storageBucket: 'flutter-tutorial-fe59f.appspot.com',
    iosClientId: '89043126170-d7fq7sqso4saehhbcrep79thkdtkrl7j.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationTutorial.RunnerTests',
  );
}
